//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddtoCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_INVOICE()
        {
            this.TBL_ORDER = new HashSet<TBL_ORDER>();
        }
    
        public int INV_ID { get; set; }
        public Nullable<int> INV_FK_USR { get; set; }
        public Nullable<System.DateTime> INV_DATE { get; set; }
        public Nullable<double> INV_TOTALIBILL { get; set; }
    
        public virtual TBL_USER TBL_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ORDER> TBL_ORDER { get; set; }
    }
}
