//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddtoCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_USER()
        {
            this.TBL_INVOICE = new HashSet<TBL_INVOICE>();
        }
    
        public int USR_ID { get; set; }
        public string USR_NAME { get; set; }
        public string USR_CONTACT { get; set; }
        public string USR_PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INVOICE> TBL_INVOICE { get; set; }
    }
}
